import os
import sys
from typing import Annotated, Literal, TypedDict
from dotenv import load_dotenv

# LangChain & LangGraph
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage, ToolMessage
from langchain_core.tools import tool
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode
from langgraph.checkpoint.memory import MemorySaver
import supabase

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not all([SUPABASE_URL, SUPABASE_KEY, GEMINI_API_KEY]):
    print("⚠️ Environment variables missing.")
    sys.exit(1)

sb_client = supabase.create_client(SUPABASE_URL, SUPABASE_KEY)

# ==========================================
# 1. GRAPH STATE
# ==========================================
class AgentState(TypedDict):
    """The state of our cognitive graph."""
    messages: Annotated[list, add_messages]

# ==========================================
# 2. TOOLS
# ==========================================
@tool
def search_guardian_db(query: str) -> str:
    """Ricerca nel database degli alert legali del Guardian. Usa questo tool per trovare le ultime novità legislative."""
    print(f"\n[Tool: search_guardian_db] -> Eseguo ricerca per: '{query}'")
    try:
        # A simple keyword-like lookup on the local DB for the prototype
        res = sb_client.table("atena_guardian_alerts").select("title, summary, impact_level").ilike('title', f'%{query}%').order("date_published", desc=True).limit(5).execute()
        data = res.data
        if not data: return "NNessun alert specifico trovato nel database Guardian per questa query."
        return "Trovati nel DB:\n" + "\n".join([f"- [{i['impact_level']}] {i['title']}: {i['summary']}" for i in data])
    except Exception as e:
        return f"Errore DB: {str(e)}"

tools = [search_guardian_db]
tool_node = ToolNode(tools)

# ==========================================
# 3. LLM INIZIALIZZAZIONE
# ==========================================
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.1,
    max_tokens=None,
    timeout=None
).bind_tools(tools)

# ==========================================
# 4. NODES (I CERVELLI)
# ==========================================
def agent_node(state: AgentState):
    """Il nodo principale (Atena). Decide se rispondere o usare un tool."""
    print("\n🧠 [Atena Agent] Sta ragionando...")
    sys_msg = SystemMessage(content="""
    Sei Atena, l'IA Legale Suprema.
    Il tuo compito è analizzare le richieste dell'utente. 
    Se ti vengono chieste informazioni legali specifiche, **usa SEMPRE il tool search_guardian_db** prima di rispondere.
    Non inventare mai leggi. Se il tool non trova nulla, dillo chiaramente.
    """)
    messages = [sys_msg] + state["messages"]
    response = llm.invoke(messages)
    return {"messages": [response]}

def fact_checker_node(state: AgentState) -> dict:
    """Nodo di Self-Reflection (Verificatore). Valuta se la risposta dell'Agente è allucinata o no."""
    print("\n🔍 [Fact Checker] Verifico la qualità della risposta...")
    
    # We grab the last message generated by the AI
    last_message = state["messages"][-1]
    
    # Only verify if it's an AI message and NOT a tool call request
    if isinstance(last_message, AIMessage) and not last_message.tool_calls:
        checker_prompt = f"""
        Sei il Fact-Checker di Atena. Leggi la risposta che Atena sta per dare all'utente.
        Se la risposta afferma fatti specifici che NON sembrano basati sul contesto dei Database o è palesemente falsa/inventata, 
        rispondi ESATTAMENTE con: "REJECT".
        Altrimenti, se la risposta è sicura e basata sui fatti, rispondi ESATTAMENTE con: "APPROVE".
        
        Risposta da valutare:
        {last_message.content}
        """
        eval_llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.0)
        evaluation = eval_llm.invoke([HumanMessage(content=checker_prompt)])
        print(f"   => Esito Verifica: {evaluation.content.strip()}")
        
        if "REJECT" in evaluation.content.upper():
            # Override Atena's message with an internal correction
            correction_msg = SystemMessage(content="[FACT CHECKER SYSTEM INJECTION] - La tua ultima risposta conteneva possibili allucinazioni. Riformula basandoti SOLO sui fatti del DB o ammetti di non sapere.")
            return {"messages": [correction_msg]}
    
    # Se va tutto bene, non modifichiamo lo state.
    return {"messages": []}

# ==========================================
# 5. EDGES (CONDIZIONI DI ROUTING)
# ==========================================
def should_continue(state: AgentState) -> Literal["tools", "fact_checker"]:
    """Decide dove andare dopo l'Agente: ai tools o alla verifica."""
    messages = state['messages']
    last_message = messages[-1]
    
    # Se l'agente ha invocato un tool, andiamo al nodo Tools
    if last_message.tool_calls:
        return "tools"
    
    # Altrimenti, andiamo al controllo fatti prima di finire
    return "fact_checker"

def check_reflection(state: AgentState) -> Literal["agent", END]:
    """Decide se finire (APPROVE) o forzare un loop (REJECT)."""
    messages = state['messages']
    last_message = messages[-1]
    
    # Se l'ultimo messaggio è il SystemMessage inserito dal Fact Checker, vuol dire che c'è stato un REJECT
    if isinstance(last_message, SystemMessage) and "FACT CHECKER" in last_message.content:
        return "agent" # Ritorna all'agente per formulare una nuova iterazione
    
    return END # La risposta era approvata, possiamo uscire al client

# ==========================================
# 6. COSTRUZIONE DEL GRAFO
# ==========================================
workflow = StateGraph(AgentState)

workflow.add_node("agent", agent_node)
workflow.add_node("tools", tool_node)
workflow.add_node("fact_checker", fact_checker_node)

# Architettura Ciclica
workflow.add_edge(START, "agent")

# Dall'Agente, decide se usare Tool o andare al Fact-Checker
workflow.add_conditional_edges("agent", should_continue, {"tools": "tools", "fact_checker": "fact_checker"})

# Dopo aver usato i tool, torna sempre all'agente per valutare i risultati
workflow.add_edge("tools", "agent")

# Dal Fact-Checker, decide se accettare o rigettare
workflow.add_conditional_edges("fact_checker", check_reflection, {"agent": "agent", END: END})

# Compiliamo con Memoria
memory = MemorySaver()
app = workflow.compile(checkpointer=memory)

# ==========================================
# 7. ESECUZIONE LIVE
# ==========================================
def main():
    print("====================================================")
    print("☸️ CICLI CONGNITIVI DI ATENA (Self-Reflection Graph) ☸️")
    print("====================================================\n")
    config = {"configurable": {"thread_id": "test_cycles_1"}}
    
    while True:
        user_input = input("⚖️ Capitano > ")
        if user_input.lower() in ['esci', 'exit']:
            break
            
        print("\n--- Inizio Flusso Graph ---")
        try:
            # stream_mode="updates" shows exactly which node just ran
            for event in app.stream({"messages": [("user", user_input)]}, config, stream_mode="updates"):
                for node_name, node_state in event.items():
                    # Check which node just outputted
                    if "messages" in node_state and len(node_state["messages"]) > 0:
                        msg = node_state["messages"][-1]
                        
                        # Only print actual string contents if it's an AI message or a Fact Checker Injection
                        if node_name == "agent" and isinstance(msg, AIMessage) and not msg.tool_calls:
                           print(f"\n[OUTPUT TENTATIVO]: {msg.content}")
                        elif node_name == "fact_checker" and isinstance(msg, SystemMessage):
                           print(f"\n[⚠️ RIFIUTO]: Atena deve correggersi.")
                           
            # The final guaranteed state message is the accepted one
            final_state = app.get_state(config)
            final_msg = final_state.values["messages"][-1]
            print(f"\n✅ [RISPOSTA FINALE DI ATENA]:\n{final_msg.content}\n")
            print("---------------------------\n")

        except Exception as e:
            print(f"❌ Errore critico nel grafo: {e}")

if __name__ == "__main__":
    main()
